version: "3.9"

services:
  backend:
    build: .
    container_name: chatterbox_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8000
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
    container_name: chatterbox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
